//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzDoc.Documents.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzDoc.Documents.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;FirstName&quot;:&quot;Mark&quot;,&quot;LastName&quot;:&quot;Rendle&quot;,&quot;Age&quot;:25}.
        /// </summary>
        internal static string JsonDocumentWithAttributesOnly {
            get {
                return ResourceManager.GetString("JsonDocumentWithAttributesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;FirstName&quot;:&quot;Mark&quot;,
        ///  &quot;LastName&quot;:&quot;Rendle&quot;,
        ///  &quot;Age&quot;:25,
        ///  &quot;List&quot;:[&quot;Zero&quot;,&quot;One&quot;]
        ///}.
        /// </summary>
        internal static string JsonDocumentWithList {
            get {
                return ResourceManager.GetString("JsonDocumentWithList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;FirstName&quot;:&quot;Mark&quot;,
        ///  &quot;LastName&quot;:&quot;Rendle&quot;,
        ///  &quot;Age&quot;:25,
        ///  &quot;Sub&quot;:{&quot;StringOne&quot;:&quot;One&quot;,&quot;NumberOne&quot;:1}
        ///}.
        /// </summary>
        internal static string JsonDocumentWithSubDocument {
            get {
                return ResourceManager.GetString("JsonDocumentWithSubDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;FirstName&quot;:&quot;Mark&quot;,
        ///  &quot;LastName&quot;:&quot;Rendle&quot;,
        ///  &quot;Age&quot;:25,
        ///  &quot;Subs&quot;:[{&quot;String&quot;:&quot;One&quot;,&quot;Number&quot;:1},{&quot;String&quot;:&quot;Two&quot;,&quot;Number&quot;:2}]
        ///}.
        /// </summary>
        internal static string JsonDocumentWithSubDocumentList {
            get {
                return ResourceManager.GetString("JsonDocumentWithSubDocumentList", resourceCulture);
            }
        }
    }
}
